os: linux
dist: focal    # Ubuntu 20.04 LTS
language: ruby

# Clone full git history for git-restore-mtime to work
git:
  depth: false

script:
  - make all

before_deploy: 
  - wget -q --output-document=firebase https://firebase.tools/bin/linux/latest
  - chmod +x firebase

deploy:
  # Firebase production deployment
  - provider: script # uses FIREBASE_TOKEN
    on:
      branch: master
    skip_cleanup: true
    script: make deploy-production
  # Firebase preview deployment
  - provider: script # uses FIREBASE_TOKEN
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = preview-*
    skip_cleanup: true
    script: make deploy-preview
